Repository symflower/eval-dev-quality, pull requests merged in 2024-07, with the labels that each got.

#229 Apply "symflower fix" to a "write-test" result of a model when it errors, so model responses can possibly be fixed
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/metrics/testing/assessments.go
  evaluate/report/collection.go
  evaluate/task/symflower-fix.go
  evaluate/task/task-code-repair.go
  evaluate/task/task-code-repair_test.go
  evaluate/task/task-write-test.go
  evaluate/task/task-write-test_test.go
  evaluate/task/task.go
  evaluate/task/test-integration/task_test.go
  evaluate/task/testing/task.go
  task/task.go
  tools/symflower.go
Labels: enhancement

#203 refactor, Move fields of "TaskWriteTests" and "TaskCodeRepair" into context object since the tasks itself are stateless
  .mockery.yml
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/report/collection_test.go
  evaluate/report/markdown_test.go
  evaluate/task/task-code-repair.go
  evaluate/task/task-code-repair_test.go
  evaluate/task/task-write-test.go
  evaluate/task/task-write-test_test.go
  evaluate/task/task.go
  evaluate/task/test-integration/task_test.go
  evaluate/task/testing/task.go
  model/capability.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/model.go
  model/symflower/symflower.go
  model/symflower/symflower_test.go
  model/testing/CapabilityRepairCode_mock_gen.go
  model/testing/CapabilityWriteTests_mock_gen.go
  model/testing/Model_mock_gen.go
  model/testing/helper.go
  task/task.go
Labels: refactor

#236 Do not run "symflower fix" if the original response failed with a timeout, so the model and the fix assessments are consistent
  evaluate/task/task-write-test.go
  evaluate/task/task-write-test_test.go
Labels: enhancement

#196 Roadmap issue template and README section about releases
  .github/ISSUE_TEMPLATE/roadmap.md
  README.md
Labels: documentation

#202 Share logging setup between tasks
  evaluate/task/task-code-repair.go
  evaluate/task/task-write-test.go
  evaluate/task/task.go
Labels: refactor

#243 Early merger for "Dump the assessments to the evaluation CSV right after running a task"
  evaluate/evaluate.go
  model/llm/llm.go
Labels: enhancement

#246 Testdata for transpiling Go into Java and Java into Go
  model/llm/llm.go
  testdata/golang/transpile/balancedBrackets/balancedBrackets.go
  testdata/golang/transpile/balancedBrackets/balancedBrackets_test.go
  testdata/golang/transpile/balancedBrackets/go.mod
  testdata/golang/transpile/balancedBrackets/implementation/BalancedBrackets.java
  testdata/golang/transpile/binarySearch/binarySearch.go
  testdata/golang/transpile/binarySearch/binarySearch_test.go
  testdata/golang/transpile/binarySearch/go.mod
  testdata/golang/transpile/binarySearch/implementation/BinarySearch.java
  testdata/golang/transpile/cascadingIfElse/cascadingIfElse.go
  testdata/golang/transpile/cascadingIfElse/cascadingIfElse_test.go
  testdata/golang/transpile/cascadingIfElse/go.mod
  testdata/golang/transpile/cascadingIfElse/implementation/CascadingIfElse.java
  testdata/golang/transpile/pascalsTriangle/go.mod
  testdata/golang/transpile/pascalsTriangle/implementation/PascalsTriangle.java
  testdata/golang/transpile/pascalsTriangle/pascalsTriangle.go
  testdata/golang/transpile/pascalsTriangle/pascalsTriangle_test.go
  testdata/golang/transpile/sort/go.mod
  testdata/golang/transpile/sort/implementation/Sort.java
  testdata/golang/transpile/sort/sort.go
  testdata/golang/transpile/sort/sort_test.go
  testdata/java/transpile/balancedBrackets/implementation/balancedBrackets.go
  testdata/java/transpile/balancedBrackets/pom.xml
  testdata/java/transpile/balancedBrackets/src/main/java/com/eval/BalancedBrackets.java
  testdata/java/transpile/balancedBrackets/src/test/java/com/eval/BalancedBracketsTest.java
  testdata/java/transpile/binarySearch/implementation/binarySearch.go
  testdata/java/transpile/binarySearch/pom.xml
  testdata/java/transpile/binarySearch/src/main/java/com/eval/BinarySearch.java
  testdata/java/transpile/binarySearch/src/test/java/com/eval/BinarySearchTest.java
  testdata/java/transpile/cascadingIfElse/implementation/cascadingIfElse.go
  testdata/java/transpile/cascadingIfElse/pom.xml
  testdata/java/transpile/cascadingIfElse/src/main/java/com/eval/CascadingIfElse.java
  testdata/java/transpile/cascadingIfElse/src/test/java/com/eval/CascadingIfElseTest.java
  testdata/java/transpile/pascalsTriangle/implementation/pascalsTriangle.go
  testdata/java/transpile/pascalsTriangle/pom.xml
  testdata/java/transpile/pascalsTriangle/src/main/java/com/eval/PascalsTriangle.java
  testdata/java/transpile/pascalsTriangle/src/test/java/com/eval/PascalsTriangleTest.java
  testdata/java/transpile/sort/implementation/sort.go
  testdata/java/transpile/sort/pom.xml
  testdata/java/transpile/sort/src/main/java/com/eval/Sort.java
  testdata/java/transpile/sort/src/test/java/com/eval/SortTest.java
Labels: enhancement

#241 Generate the "models-summed.csv" and "language-summed.csv" files based on the "evaluation.csv" file
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/report/collection.go
  evaluate/report/collection_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  model/testing/helper.go
Labels: enhancement

#259 Change the "code-repair" and "write-tests" task prompt to enforce the generated code to be inside code fences, to ensure we can extract the code from the LLMs response
  model/llm/llm.go
  model/llm/llm_test.go
Labels: enhancement

#261 New assessment to hold the maximum reachable executable files
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/report/csv_test.go
  evaluate/task/task-code-repair.go
  evaluate/task/task-code-repair_test.go
  evaluate/task/task-write-test.go
  evaluate/task/task-write-test_test.go
  evaluate/task/test-integration/task_test.go
Labels: enhancement

#255 Add the commit revision to binary/reports/docker
  .github/workflows/branch.yml
  .github/workflows/docker.yml
  Makefile
  cmd/eval-dev-quality/cmd/command.go
  cmd/eval-dev-quality/cmd/command_test.go
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/version.go
  cmd/eval-dev-quality/cmd/version_test.go
  evaluate/report/markdown.go
  evaluate/report/markdown_test.go
  evaluate/version.go
Labels: enhancement

#262 Make the Java Knapsack inner class static, so it is easier for LLMs to solve
  testdata/java/light/src/main/java/com/eval/Knapsack.java
Labels: enhancement

#256 Remove the summed CSVs and model's cost and human-readable name, since they will be handled afterwards with tooling
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  model/llm/llm.go
  model/model.go
  model/symflower/symflower.go
  model/testing/Model_mock_gen.go
  model/testing/helper.go
  provider/ollama/ollama.go
  provider/openrouter/openrouter.go
Labels: enhancement

#264 Early merger for the transpilation task and update README
  README.md
  evaluate/task/symflower-fix.go
  evaluate/task/task-code-repair.go
  evaluate/task/task-write-test.go
  evaluate/task/task.go
  testdata/golang/transpile/isSorted/go.mod
  testdata/golang/transpile/isSorted/implementation/IsSorted.java
  testdata/golang/transpile/isSorted/isSorted.go
  testdata/golang/transpile/isSorted/isSorted_test.go
  testdata/java/transpile/isSorted/implementation/isSorted.go
  testdata/java/transpile/isSorted/pom.xml
  testdata/java/transpile/isSorted/src/main/java/com/eval/IsSorted.java
  testdata/java/transpile/isSorted/src/test/java/com/eval/IsSortedTest.java
  testdata/java/transpile/pascalsTriangle/src/main/java/com/eval/PascalsTriangle.java
Labels: documentation, enhancement

#268 Use Linux file paths on prompts even if the evaluation is running on a Windows machine, so the prompt is always the same
  model/llm/llm.go
  model/llm/llm_test.go
Labels: enhancement

#265 Check if the testdata repository is valid before running the evaluation, so it is checked just once
  evaluate/evaluate.go
  evaluate/task/repository.go
  evaluate/task/task-code-repair.go
  evaluate/task/task-code-repair_test.go
  evaluate/task/task-write-test.go
  evaluate/task/task-write-test_test.go
  evaluate/task/task.go
  evaluate/task/testing/task.go
  task/task.go
Labels: enhancement

#269 Shut down the Ollama service if there are no Ollama models to evaluate, to avoid unnecessary processes being opened
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
Labels: enhancement

#272 Copy cluster data and documentation update
  README.md
  cmd/eval-dev-quality/cmd/evaluate.go
  conf/kube/job.yml
  conf/kube/storage-access.yml
  docs/kubernetes/README.md
  docs/kubernetes/job.yml
Labels: enhancement

#271 Introduce the "report" command to combine multiple evaluations into a single file
  cmd/eval-dev-quality/cmd/command.go
  cmd/eval-dev-quality/cmd/command_test.go
  cmd/eval-dev-quality/cmd/report.go
  cmd/eval-dev-quality/cmd/report_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
Labels: enhancement

#267 fix, Define a timeout for the "symflower unit-tests" command, so ensure the execution does not take too much time
  model/symflower/symflower.go
  model/symflower/symflower_test.go
Labels: bug

#274 Always numerize the result path of containerized runs to avoid I/O sync problems
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
Labels: bug

#277 fix, Handle inconsistent timout error on Windows
  model/symflower/symflower_test.go
Labels: bug

#279 Use a pinned version for Java 11 dependency
  Dockerfile
Labels: bug

#275 fix, Use the correct Maven snapshot format in the Java test data, to have a cleaner output without warnings
  testdata/java/light/pom.xml
  testdata/java/mistakes/importMissing/pom.xml
  testdata/java/mistakes/openingBracketMissing/pom.xml
  testdata/java/mistakes/syntaxErrorTypeMissing/pom.xml
  testdata/java/mistakes/typeUnknown/pom.xml
  testdata/java/mistakes/variableUnknown/pom.xml
  testdata/java/plain/pom.xml
  testdata/java/transpile/balancedBrackets/pom.xml
  testdata/java/transpile/binarySearch/pom.xml
  testdata/java/transpile/cascadingIfElse/pom.xml
  testdata/java/transpile/isSorted/pom.xml
  testdata/java/transpile/pascalsTriangle/pom.xml
Labels: bug

#281 fix, Ignore git and Maven directories when validating the code repair repository, since they do not need any validation
  evaluate/task/task-code-repair.go
  evaluate/task/task-code-repair_test.go
Labels: bug

#258 Let the "report" command also generate a markdown report for the combined evaluations
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  cmd/eval-dev-quality/cmd/report.go
  cmd/eval-dev-quality/cmd/report_test.go
  evaluate/report/collection.go
  evaluate/report/collection_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  evaluate/report/markdown.go
  evaluate/report/markdown_test.go
Labels: enhancement

#226 Task for code transpilation, so models can transpile Go code to Java and back
  .mockery.yml
  README.md
  cmd/eval-dev-quality/cmd/report_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/report/csv_test.go
  evaluate/task/symflower-fix.go
  evaluate/task/task-code-repair.go
  evaluate/task/task-transpile.go
  evaluate/task/task-transpile_test.go
  evaluate/task/task-write-test.go
  evaluate/task/task-write-test_test.go
  evaluate/task/task.go
  language/golang/language.go
  language/golang/language_test.go
  language/java/language.go
  language/java/language_test.go
  language/language.go
  language/testing/Language_mock_gen.go
  language/testing/language.go
  model/capability.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/symflower/symflower_test.go
  model/testing/CapabilityTranspile_mock_gen.go
  model/testing/helper.go
  testdata/golang/transpile/repository.json
  testdata/java/transpile/repository.json
Labels: enhancement

#284 Pull ollama models
  .mockery.yml
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  log/logger.go
  provider/ollama/ollama.go
  provider/provider.go
  provider/testing/Puller_mock_gen.go
  tools/ollama.go
Labels: enhancement

#288 Write openrouter models to CSV and reject models that we want to ignore automatically
  scripts/openrouter-models/main.go
Labels: enhancement

#287 Store repositories in JSON
  cmd/eval-dev-quality/cmd/config.go
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/task/repository.go
Labels: enhancement

#292 Satisfy Kubernetes convention to only have alphanumeric characters and "-" in job names
  cmd/eval-dev-quality/cmd/evaluate.go
Labels: bug

#294 Update to latest Symflower version for improved static code repair
  tools/symflower.go
Labels: enhancement

#297 Update README to 0.5.0 blog post
  README.md
Labels: documentation
