Repository symflower/eval-dev-quality, pull requests merged in 2024-06, with the labels that each got.

#124 More "write tests" task cases with more complex logic
  README.md
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/metrics/category.go
  evaluate/metrics/category_test.go
  evaluate/report/csv_test.go
  evaluate/repository.go
  evaluate/repository_test.go
  language/coverage.go
  language/golang/language.go
  language/golang/language_test.go
  language/java/language.go
  language/java/language_test.go
  language/language.go
  language/testing/Language_mock_gen.go
  model/symflower/symflower_test.go
  testdata/golang/light/balancedBrackets.go
  testdata/golang/light/binarySearch.go
  testdata/golang/light/callLoopConditionsOftenEnough.go
  testdata/golang/light/cascadingIfElse.go
  testdata/golang/light/collatzCalculator.go
  testdata/golang/light/conditionsAnd.go
  testdata/golang/light/equilibriumIndices.go
  testdata/golang/light/forLoop.go
  testdata/golang/light/go.mod
  testdata/golang/light/jacobiSymbol.go
  testdata/golang/light/klarnerRadoSequence.go
  testdata/golang/light/knapsack.go
  testdata/golang/light/largestProperDivisor.go
  testdata/golang/light/magicSquareOdd.go
  testdata/golang/light/matchBytes.go
  testdata/golang/light/pascalsTriangle.go
  testdata/golang/light/phoneNumber.go
  testdata/golang/light/simpleIfElse.go
  testdata/golang/light/simpleSwitchWithReturn.go
  testdata/golang/light/sort.go
  testdata/golang/light/typeArrayAccess.go
  testdata/golang/light/typeArrayConsecutiveAccess.go
  testdata/golang/light/typeArrayMultidimensionalArrayLength.go
  testdata/golang/light/validateDate.go
  testdata/java/light/pom.xml
  testdata/java/light/src/main/java/com/eval/BalancedBrackets.java
  testdata/java/light/src/main/java/com/eval/BinarySearch.java
  testdata/java/light/src/main/java/com/eval/CollatzCalculator.java
  testdata/java/light/src/main/java/com/eval/EqulibriumIndices.java
  testdata/java/light/src/main/java/com/eval/JacobiSymbol.java
  testdata/java/light/src/main/java/com/eval/KlarnerRadoSequence.java
  testdata/java/light/src/main/java/com/eval/Knapsack.java
  testdata/java/light/src/main/java/com/eval/LargestProperDivisor.java
  testdata/java/light/src/main/java/com/eval/MagicSquareOdd.java
  testdata/java/light/src/main/java/com/eval/MatchBytes.java
  testdata/java/light/src/main/java/com/eval/PascalsTriangle.java
  testdata/java/light/src/main/java/com/eval/PhoneNumber.java
  testdata/java/light/src/main/java/com/eval/ValidDate.java
Labels: enhancement

#150 Add the testify package dependency to the Golang light repository, so `symflower test` can execute the generated tests
  model/symflower/symflower.go
  testdata/golang/light/go.mod
Labels: enhancement

#153 Download Go dependencies when executing tests
  evaluate/evaluate_test.go
  language/golang/language.go
  model/symflower/symflower.go
Labels: bug

#155 Test file path needs to be OS aware
  language/java/language.go
  language/java/language_test.go
Labels: bug

#172 fix, Use a backoff for retrying LLM queries because it seems that some LLMs need longer to recover
  model/llm/llm.go
  tools/ollama.go
Labels: bug

#171 fix, Fail tests immediately in case tool is outdated or unusable
  .mockery.yml
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/repository_test.go
  model/symflower/symflower_test.go
  provider/ollama/ollama_test.go
  tools/testing/Tool_mock_gen.go
  tools/testing/helper.go
  tools/testing/tools.go
  tools/testing/tools_test.go
Labels: bug

#177 fix, Allow arbitrary content immediately after code tag
  model/llm/prompt/parse.go
  model/llm/prompt/parse_test.go
Labels: bug

#179 fix, Rename result directory if it already exists
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  util/io.go
  util/io_test.go
Labels: bug

#162 Check for Java and Go compilation errors when building a project, for further compile error code repairing task
  language/golang/language.go
  language/golang/language_test.go
  language/java/language.go
  language/java/language_test.go
  language/language.go
  language/testing/Language_mock_gen.go
  testdata/golang/mistakes/functionWithoutOpeningBracket.go
  testdata/golang/mistakes/go.mod
  testdata/java/mistakes/pom.xml
  testdata/java/mistakes/src/main/java/com/eval/MethodWithoutOpeningBracket.java
Labels: enhancement

#183 Extend temporary repository tests to Windows
  evaluate/repository_test.go
Labels: refactor, OS:Windows, CI

#188 fix, Define a timeout for the "symflower test" command, so ensure the execution does not take too much time
  cmd/eval-dev-quality/cmd/evaluate.go
  language/golang/language.go
  language/java/language.go
  language/language.go
  util/exec_test.go
Labels: bug

#192 Early merger for code repair task
  evaluate/repository_test.go
  language/golang/language_test.go
  language/java/language_test.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/symflower/symflower.go
  task/task.go
  testdata/golang/light/repository.json
  testdata/golang/mistakes/functionWithoutOpeningBracket.go
  testdata/golang/mistakes/go.mod
  testdata/golang/mistakes/importMissing/go.mod
  testdata/golang/mistakes/importMissing/importMissing.go
  testdata/golang/mistakes/importMissing/importMissing_test.go
  testdata/golang/mistakes/openingBracketMissing/go.mod
  testdata/golang/mistakes/openingBracketMissing/openingBracketMissing.go
  testdata/golang/mistakes/openingBracketMissing/openingBracketMissing_test.go
  testdata/golang/mistakes/repository.json
  testdata/golang/mistakes/syntaxErrorTypeMissing/go.mod
  testdata/golang/mistakes/syntaxErrorTypeMissing/syntaxErrorTypeMissing.go
  testdata/golang/mistakes/syntaxErrorTypeMissing/syntaxErrorTypeMissing_test.go
  testdata/golang/mistakes/typeUnknown/go.mod
  testdata/golang/mistakes/typeUnknown/typeUnknown.go
  testdata/golang/mistakes/typeUnknown/typeUnknown_test.go
  testdata/golang/mistakes/variableUnknown/go.mod
  testdata/golang/mistakes/variableUnknown/variableUnknown.go
  testdata/golang/mistakes/variableUnknown/variableUnknown_test.go
  testdata/golang/plain/repository.json
  testdata/java/light/repository.json
  testdata/java/mistakes/importMissing/pom.xml
  testdata/java/mistakes/importMissing/src/main/java/com/eval/ImportMissing.java
  testdata/java/mistakes/importMissing/src/test/java/com/eval/ImportMissingTest.java
  testdata/java/mistakes/openingBracketMissing/pom.xml
  testdata/java/mistakes/openingBracketMissing/src/main/java/com/eval/OpeningBracketMissing.java
  testdata/java/mistakes/openingBracketMissing/src/test/java/com/eval/OpeningBracketMissingTest.java
  testdata/java/mistakes/pom.xml
  testdata/java/mistakes/repository.json
  testdata/java/mistakes/src/main/java/com/eval/MethodWithoutOpeningBracket.java
  testdata/java/mistakes/syntaxErrorTypeMissing/pom.xml
  testdata/java/mistakes/syntaxErrorTypeMissing/src/main/java/com/eval/SyntaxErrorTypeMissing.java
  testdata/java/mistakes/syntaxErrorTypeMissing/src/test/java/com/eval/SyntaxErrorTypeMissingTest.java
  testdata/java/mistakes/typeUnknown/pom.xml
  testdata/java/mistakes/typeUnknown/src/main/java/com/eval/TypeUnknown.java
  testdata/java/mistakes/typeUnknown/src/test/java/com/eval/TypeUnknownTest.java
  testdata/java/mistakes/variableUnknown/pom.xml
  testdata/java/mistakes/variableUnknown/src/main/java/com/eval/VariableUnknown.java
  testdata/java/mistakes/variableUnknown/src/test/java/com/eval/VariableUnknownTest.java
  testdata/java/plain/repository.json
Labels: enhancement

#191 fix, Retry querying Openrouter models cause that sometimes fails
  provider/openrouter/openrouter.go
Labels: bug, flaky

#197 Task interface to accommodate different types of tasks
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/report/collection_test.go
  evaluate/report/csv_test.go
  evaluate/repository_test.go
  evaluate/task/repository.go
  evaluate/task/repository_test.go
  evaluate/task/task-write-test.go
  evaluate/task/task-write-test_test.go
  evaluate/task/task.go
  evaluate/task/test-integration/task_test.go
  evaluate/task/testing/task.go
  model/llm/llm.go
  model/symflower/symflower.go
  model/testing/helper.go
  task/task.go
Labels: enhancement

#184 Explicit windows test case for Java test path logic
  language/java/language_test.go
Labels: bug

#182 fix, Default to all repositories if none are selected in CLI
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate.go
  language/language.go
Labels: bug, refactor

#216 Extract model costs into log and CSVs, so the pricing information is always available
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  model/llm/llm.go
  model/model.go
  model/symflower/symflower.go
  model/testing/Model_mock_gen.go
  model/testing/helper.go
  provider/openrouter/openrouter.go
  provider/openrouter/openrouter_test.go
Labels: enhancement

#217 Extract model names, to obtain a human-readable name for each model
  cmd/eval-dev-quality/cmd/evaluate.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  model/llm/llm.go
  model/model.go
  model/symflower/symflower.go
  model/testing/Model_mock_gen.go
  model/testing/helper.go
  provider/ollama/ollama.go
  provider/openrouter/openrouter.go
Labels: enhancement

#223 Log the coverage objects, so this information is available and not lost
  cmd/eval-dev-quality/cmd/evaluate_test.go
  language/coverage.go
  language/golang/language.go
  language/java/language.go
Labels: enhancement

#211 Docker runtime
  cmd/eval-dev-quality/cmd/evaluate.go
  util/exec.go
  util/exec_test.go
Labels: enhancement
