Repository symflower/eval-dev-quality, pull requests merged in 2024-08, with the labels that each got.

#303 Bump symflower version to stay on the latest version possible
  tools/symflower.go
Labels: enhancement

#308 Copying docker results did not work without setting the `result-path` parameter
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
Labels: bug

#311 Introduce the Ruby language
  language/golang/language.go
  language/java/language.go
  language/language.go
  language/ruby/language.go
  language/ruby/language_test.go
  testdata/ruby/plain/lib/plain.rb
Labels: enhancement

#314 Free Github runner disk space by removing unnecessary pre packaged stuff
  .github/workflows/test.yml
Labels: enhancement, CI

#313 Do not register Ruby language yet, since the test execution feature is still in progress
  language/ruby/language.go
Labels: enhancement

#298 Store models meta information in a CSV file, so it can be further used in data visualization
  cmd/eval-dev-quality/cmd/report.go
  cmd/eval-dev-quality/cmd/report_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  model/llm/llm.go
  model/model.go
  model/symflower/symflower.go
  model/testing/Model_mock_gen.go
  provider/openrouter/openrouter.go
Labels: enhancement

#315 Light repository for Ruby
  testdata/ruby/light/Gemfile
  testdata/ruby/light/Rakefile
  testdata/ruby/light/lib/balanced_brackets.rb
  testdata/ruby/light/lib/binary_search.rb
  testdata/ruby/light/lib/call_loop_conditions_often_enough.rb
  testdata/ruby/light/lib/cascading_if_else.rb
  testdata/ruby/light/lib/collatz_calculator.rb
  testdata/ruby/light/lib/conditions_and.rb
  testdata/ruby/light/lib/equilibrium_indices.rb
  testdata/ruby/light/lib/for_loop.rb
  testdata/ruby/light/lib/jacobi_symbol.rb
  testdata/ruby/light/lib/klarner_rado_sequence.rb
  testdata/ruby/light/lib/knapsack.rb
  testdata/ruby/light/lib/largest_proper_divisor.rb
  testdata/ruby/light/lib/magic_square_odd.rb
  testdata/ruby/light/lib/match_bytes.rb
  testdata/ruby/light/lib/pascals_triangle.rb
  testdata/ruby/light/lib/phone_number.rb
  testdata/ruby/light/lib/simple_if_else.rb
  testdata/ruby/light/lib/simple_switch_with_return.rb
  testdata/ruby/light/lib/sort.rb
  testdata/ruby/light/lib/type_array_access.rb
  testdata/ruby/light/lib/type_array_consecutive_access.rb
  testdata/ruby/light/lib/type_array_multidimensional_array_length.rb
  testdata/ruby/light/lib/validate_date.rb
  testdata/ruby/plain/Gemfile
  testdata/ruby/plain/Rakefile
Labels: enhancement

#309 Add Ruby as Dependency to the Docker container
  Dockerfile
Labels: enhancement

#321 fix, Score with passing tests in code-repair task cause coverage can be cheated
  evaluate/task/task-code-repair.go
  evaluate/task/task-code-repair_test.go
Labels: bug

#322 fix, Prefix openrouter model with provider ID only once
  provider/openrouter/openrouter.go
  provider/openrouter/openrouter_test.go
Labels: bug

#323 Use new Symflower version which reduces error output of the "fix" command
  tools/symflower.go
Labels: enhancement

#316 Mistakes repository for Ruby
  testdata/ruby/mistakes/argumentMissing/Gemfile
  testdata/ruby/mistakes/argumentMissing/Rakefile
  testdata/ruby/mistakes/argumentMissing/lib/argument_missing.rb
  testdata/ruby/mistakes/argumentMissing/test/argument_missing_test.rb
  testdata/ruby/mistakes/argumentMissing/test/test_init.rb
  testdata/ruby/mistakes/endKeywordMissing/Gemfile
  testdata/ruby/mistakes/endKeywordMissing/Rakefile
  testdata/ruby/mistakes/endKeywordMissing/lib/end_keyword_missing.rb
  testdata/ruby/mistakes/endKeywordMissing/test/end_keyword_missing_test.rb
  testdata/ruby/mistakes/endKeywordMissing/test/test_init.rb
  testdata/ruby/mistakes/importMissing/Gemfile
  testdata/ruby/mistakes/importMissing/Rakefile
  testdata/ruby/mistakes/importMissing/lib/import_missing.rb
  testdata/ruby/mistakes/importMissing/test/import_missing_test.rb
  testdata/ruby/mistakes/importMissing/test/test_init.rb
  testdata/ruby/mistakes/typeUnknown/Gemfile
  testdata/ruby/mistakes/typeUnknown/Rakefile
  testdata/ruby/mistakes/typeUnknown/lib/type_unknown.rb
  testdata/ruby/mistakes/typeUnknown/test/test_init.rb
  testdata/ruby/mistakes/typeUnknown/test/type_unknown_test.rb
  testdata/ruby/mistakes/variableUnknown/Gemfile
  testdata/ruby/mistakes/variableUnknown/Rakefile
  testdata/ruby/mistakes/variableUnknown/lib/variable_unknown.rb
  testdata/ruby/mistakes/variableUnknown/test/test_init.rb
  testdata/ruby/mistakes/variableUnknown/test/variable_unknown_test.rb
Labels: enhancement

#318 Transpile repository for Ruby
  testdata/golang/transpile/balancedBrackets/implementation/balanced_brackets.rb
  testdata/golang/transpile/binarySearch/implementation/binary_search.rb
  testdata/golang/transpile/cascadingIfElse/implementation/cascading_if_else.rb
  testdata/golang/transpile/isSorted/implementation/sort.rb
  testdata/golang/transpile/pascalsTriangle/implementation/pascals_triangle.rb
  testdata/java/transpile/balancedBrackets/implementation/balanced_brackets.rb
  testdata/java/transpile/binarySearch/implementation/binary_search.rb
  testdata/java/transpile/cascadingIfElse/implementation/cascading_if_else.rb
  testdata/java/transpile/isSorted/implementation/sort.rb
  testdata/java/transpile/pascalsTriangle/implementation/pascals_triangle.rb
  testdata/ruby/transpile/balancedBrackets/Gemfile
  testdata/ruby/transpile/balancedBrackets/Rakefile
  testdata/ruby/transpile/balancedBrackets/implementation/BalancedBrackets.java
  testdata/ruby/transpile/balancedBrackets/implementation/balancedBrackets.go
  testdata/ruby/transpile/balancedBrackets/lib/balanced_brackets.rb
  testdata/ruby/transpile/balancedBrackets/test/balanced_brackets_test.rb
  testdata/ruby/transpile/balancedBrackets/test/test_init.rb
  testdata/ruby/transpile/binarySearch/Gemfile
  testdata/ruby/transpile/binarySearch/Rakefile
  testdata/ruby/transpile/binarySearch/implementation/BinarySearch.java
  testdata/ruby/transpile/binarySearch/implementation/binarySearch.go
  testdata/ruby/transpile/binarySearch/lib/binary_search.rb
  testdata/ruby/transpile/binarySearch/test/binary_search_test.rb
  testdata/ruby/transpile/binarySearch/test/test_init.rb
  testdata/ruby/transpile/cascadingIfElse/Gemfile
  testdata/ruby/transpile/cascadingIfElse/Rakefile
  testdata/ruby/transpile/cascadingIfElse/implementation/CascadingIfElse.java
  testdata/ruby/transpile/cascadingIfElse/implementation/cascadingIfElse.go
  testdata/ruby/transpile/cascadingIfElse/lib/cascading_if_else.rb
  testdata/ruby/transpile/cascadingIfElse/test/cascading_if_else_test.rb
  testdata/ruby/transpile/cascadingIfElse/test/test_init.rb
  testdata/ruby/transpile/isSorted/Gemfile
  testdata/ruby/transpile/isSorted/Rakefile
  testdata/ruby/transpile/isSorted/implementation/Sort.java
  testdata/ruby/transpile/isSorted/implementation/sort.go
  testdata/ruby/transpile/isSorted/lib/sort.rb
  testdata/ruby/transpile/isSorted/test/sort_test.rb
  testdata/ruby/transpile/isSorted/test/test_init.rb
  testdata/ruby/transpile/pascalsTriangle/Gemfile
  testdata/ruby/transpile/pascalsTriangle/Rakefile
  testdata/ruby/transpile/pascalsTriangle/implementation/PascalsTriangle.java
  testdata/ruby/transpile/pascalsTriangle/implementation/pascalsTriangle.go
  testdata/ruby/transpile/pascalsTriangle/lib/pascals_triangle.rb
  testdata/ruby/transpile/pascalsTriangle/test/pascals_triangle_test.rb
  testdata/ruby/transpile/pascalsTriangle/test/test_init.rb
Labels: enhancement

#317 Infer the language we want to transpile from the file extension, so other languages are supported for transpilation
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/task/task-code-repair_test.go
  evaluate/task/task-transpile.go
  evaluate/task/task-transpile_test.go
  evaluate/task/task-write-test_test.go
  evaluate/task/testing/task.go
  language/language.go
  language/ruby/language.go
Labels: enhancement

#326 Define the mistakes logic for Ruby
  language/golang/language_test.go
  language/java/language_test.go
  language/ruby/language.go
  language/ruby/language_test.go
  language/testing/language.go
Labels: enhancement

#332 fix, Use another example for the missing import package, since the current one does not work because Ruby auto-loads the JSON module
  testdata/ruby/mistakes/importMissing/lib/import_missing.rb
  testdata/ruby/mistakes/importMissing/test/import_missing_test.rb
Labels: bug

#331 Throw an error when trying to use a configuration file with containerized runtimes
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  util/exec_test.go
Labels: bug

#333 Set up ruby inside the Github Actions Workflow
  .github/workflows/test.yml
Labels: CI
