Repository symflower/eval-dev-quality, pull requests merged in 2024-09, with the labels that each got.

#327 Finalize Ruby support
  README.md
  evaluate/task/repository.go
  evaluate/task/repository_test.go
  evaluate/task/task-code-repair_test.go
  evaluate/task/task-transpile.go
  evaluate/task/task-transpile_test.go
  evaluate/task/task-write-test_test.go
  evaluate/task/task.go
  language/ruby/language.go
  language/ruby/language_test.go
  model/testing/helper.go
  testdata/ruby/light/repository.json
  testdata/ruby/mistakes/argumentMissing/test/argument_missing_test.rb
  testdata/ruby/mistakes/endKeywordMissing/test/end_keyword_missing_test.rb
  testdata/ruby/mistakes/importMissing/test/import_missing_test.rb
  testdata/ruby/mistakes/repository.json
  testdata/ruby/mistakes/typeUnknown/test/type_unknown_test.rb
  testdata/ruby/mistakes/variableUnknown/test/variable_unknown_test.rb
  testdata/ruby/plain/repository.json
  testdata/ruby/transpile/balancedBrackets/test/balanced_brackets_test.rb
  testdata/ruby/transpile/binarySearch/test/binary_search_test.rb
  testdata/ruby/transpile/cascadingIfElse/test/cascading_if_else_test.rb
  testdata/ruby/transpile/isSorted/test/sort_test.rb
  testdata/ruby/transpile/pascalsTriangle/test/pascals_triangle_test.rb
  testdata/ruby/transpile/repository.json
  tools/symflower.go
Labels: enhancement

#339 Update symflower.com with DevQualityEval entries
  .github/ISSUE_TEMPLATE/roadmap.md
Labels: documentation

#342 Issue templates for bugs and feature requests
  .github/ISSUE_TEMPLATE/1-bug.yaml
  .github/ISSUE_TEMPLATE/2-enhancement.md
  .github/ISSUE_TEMPLATE/3-roadmap.md
  evaluate/version.go
Labels: documentation

#345 Overhaul bug and feature request issue templates
  .github/ISSUE_TEMPLATE/1-bug.yaml
  .github/ISSUE_TEMPLATE/2-enhancement.md
  .github/ISSUE_TEMPLATE/2-enhancement.yaml
  .github/ISSUE_TEMPLATE/3-roadmap.md
  Makefile
  scripts/evaluation/stats.sh
  scripts/max-score/run.sh
Labels: documentation

#346 fix, Input form template does not allow special rendering
  .github/ISSUE_TEMPLATE/1-bug.yaml
Labels: bug, documentation
