Repository symflower/eval-dev-quality, pull requests merged in 2024-05, with the labels that each got.

#84 Use the most cost-effective model that is still good for usage showcase because Claude Opus is super expensive
  README.md
Labels: enhancement

#85 Replace model dependent evaluation result with report file since that contains all the evaluation information
  README.md
Labels: enhancement

#86 Reduce fluff of intro to a minimum, and summary CSVs for the v0.4.0 results
  README.md
  docs/reports/v0.4.0/evaluation.csv
  docs/reports/v0.4.0/golang-summed.csv
  docs/reports/v0.4.0/java-summed.csv
  docs/reports/v0.4.0/models-summed.csv
Labels: enhancement

#89 Award 10 points for reaching maximal coverage instead of 1 and note result differences in evaluation README
  cmd/eval-dev-quality/cmd/evaluate_test.go
  docs/reports/v0.4.0/README.md
  evaluate/metrics/assessment.go
  evaluate/metrics/category.go
  evaluate/metrics/category_test.go
  evaluate/repository.go
  evaluate/repository_test.go
  model/llm/prompt/parse.go
Labels: enhancement

#94 Additional CSVs to sum up metrics for all models overall and per language
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/report/collection.go
  evaluate/report/collection_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  evaluate/report/markdown.go
  evaluate/report/markdown_test.go
Labels: enhancement

#99 Sort map by model before creating the CSV output
  evaluate/report/csv.go
Labels: bug

#104 fix, Let Windows CI error on failures, and inject API tokens only once per provider
  .github/workflows/go.yml
  cmd/eval-dev-quality/cmd/evaluate.go
Labels: bug

#95 Ollama tool installation
  cmd/eval-dev-quality/cmd/command.go
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  cmd/eval-dev-quality/cmd/install-tools.go
  cmd/eval-dev-quality/cmd/install-tools_test.go
  evaluate/report/collection.go
  evaluate/report/collection_test.go
  evaluate/report/csv.go
  evaluate/report/markdown.go
  provider/openrouter/openrouter.go
  provider/provider.go
  provider/symflower/symflower.go
  provider/testing/Provider_mock_gen.go
  provider/testing/helper.go
  tools/install.go
  tools/install_test.go
  tools/ollama.go
  tools/ollama_test.go
  tools/symflower.go
  tools/symflower_test.go
  tools/tools.go
Labels: enhancement

#115 Prepare for Ollama provider
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  language/golang/language.go
  language/java/language.go
  model/symflower/symflower.go
  tools/ollama.go
  tools/symflower.go
  util/exec.go
Labels: enhancement

#96 Support Ollama provider
  Makefile
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  go.mod
  provider/ollama/ollama.go
  provider/ollama/ollama_test.go
  provider/provider.go
  tools/ollama.go
  tools/ollama_test.go
  util/exec.go
Labels: enhancement

#106 Measure processing time of model responses
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/metrics/testing/assessments.go
  evaluate/report/csv_test.go
  evaluate/repository.go
  model/llm/llm.go
  model/symflower/symflower.go
Labels: enhancement

#109 Multiple runs in a single evaluation
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
Labels: enhancement

#122 Introduce an "ID" method to the tool interface
  tools/install.go
  tools/install_test.go
  tools/ollama.go
  tools/symflower.go
  tools/tools.go
Labels: enhancement

#125 Allow to retry a model when it errors
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  model/llm/llm.go
  model/model.go
Labels: enhancement

#132 Clean up query attempt code
  cmd/eval-dev-quality/cmd/evaluate.go
  model/llm/llm.go
  model/model.go
Labels: enhancement

#133 Make sure to use uint64 consistently for metrics and scoring, and allow more task cases by always working on a clean repository
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/metrics/category.go
  evaluate/metrics/category_test.go
  evaluate/report/collection.go
  evaluate/report/collection_test.go
  evaluate/report/markdown.go
  evaluate/repository.go
  model/llm/llm.go
  model/symflower/symflower.go
Labels: bug, enhancement

#136 refactor, Move evaluation logic into evaluation package for isolation of concern
  cmd/eval-dev-quality/cmd/evaluate.go
  evaluate/evaluate.go
  evaluate/report/collection.go
Labels: refactor

#137 Remove the need to change the provider registery in tests to make test code concurrency safe
  .vscode/settings.json
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  model/llm/llm.go
Labels: enhancement

#129 Do not cancel successive runs if previous runs had problems
  evaluate/evaluate.go
  evaluate/evaluate_test.go
Labels: bug

#138 refactor, Move the error used in the evaluation tests to a variable, to avoid copying it the test suites
  evaluate/evaluate_test.go
Labels: refactor

#114 Use Git to avoid copying the repository on each model run
  .github/workflows/go.yml
  evaluate/evaluate.go
  evaluate/repository.go
  evaluate/repository_test.go
Labels: enhancement

#120 Option to execute multiple runs non-interleaved
  cmd/eval-dev-quality/cmd/evaluate.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
Labels: enhancement

#144 Require at least symflower v36800
  tools/symflower.go
Labels: bug

#142 Track how many characters were present in a model response and generated test files
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/metrics/testing/assessments.go
  evaluate/report/csv_test.go
  evaluate/repository_test.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/symflower/symflower.go
  model/symflower/symflower_test.go
Labels: enhancement

#146 Use empty Git config in temporary repositories
  evaluate/evaluate.go
  evaluate/repository.go
  evaluate/repository_test.go
Labels: bug

#148 Reset repository per task
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/metrics/testing/assessments.go
  evaluate/repository.go
  evaluate/repository_test.go
  model/testing/helper.go
  util/exec.go
Labels: bug
