Repository symflower/eval-dev-quality, pull requests merged in 2024-04, with the labels that each got.

#21 First version of a simple README for the repository on motivation, installation, usage and contributing
  Makefile
  README.md
Labels: documentation, enhancement

#36 Assessment
  cmd/eval-dev-quality/cmd/evaluate.go
  evaluate/metrics/assessment.go
  evaluate/metrics/metrics.go
  evaluate/metrics/metrics_test.go
  evaluate/repository.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/llm/prompt/parse.go
  model/llm/prompt/parse_test.go
  model/model.go
  model/symflower/symflower.go
  model/symflower/symflower_test.go
Labels: enhancement

#37 Allow to add to existing assessment collection
  Makefile
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/metrics/metrics.go
  evaluate/repository.go
  scripts/editor.sh
Labels: enhancement

#38 Move existing metrics to assessments
  cmd/eval-dev-quality/cmd/evaluate.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/metrics/metrics.go
  evaluate/metrics/metrics_test.go
  evaluate/repository.go
Labels: refactor

#45 Remove debugging output, and fix packages arguments of Make
  Makefile
  language/golang.go
Labels: bug

#46 Integration testing for the binary
  cmd/eval-dev-quality/cmd/command.go
  cmd/eval-dev-quality/cmd/command_test.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  cmd/eval-dev-quality/main.go
  evaluate/metrics/testing/assessments.go
  evaluate/repository.go
  language/golang.go
  language/golang_test.go
  language/language.go
  log/logger.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/llm/prompt/parse.go
  model/llm/prompt/parse_test.go
  model/model.go
  model/symflower/symflower.go
  model/symflower/symflower_test.go
  provider/provider.go
  util/exec.go
Labels: enhancement

#48 Categorization
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/metrics/category.go
  evaluate/metrics/category_test.go
  evaluate/report/collection.go
  evaluate/report/collection_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  language/testing/mock.go
  model/llm/prompt/parse.go
  model/testing/mock.go
  util/slices.go
  util/slices_test.go
Labels: enhancement

#50 Automatically install Symflower with a fixed version for the CI, development environment and evaluation benchmark
  .github/workflows/go.yml
  Makefile
  cmd/eval-dev-quality/cmd/command.go
  cmd/eval-dev-quality/cmd/command_test.go
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/install-tools.go
  cmd/eval-dev-quality/cmd/install-tools_test.go
  log/logger.go
  tools/symflower.go
  tools/symflower_test.go
  tools/tools.go
  tools/tools_test.go
Labels: enhancement

#54 Log where we are saving results to
  cmd/eval-dev-quality/cmd/evaluate.go
Labels: enhancement

#56 fix, Lock Symflower installations to make sure two evalatuions do not install at the same time
  go.mod
  go.sum
  tools/symflower.go
Labels: bug

#55 refactor, Consistent naming conventions for languages, models and providers
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/install-tools.go
  evaluate/metrics/assessment.go
  evaluate/metrics/category.go
  evaluate/repository.go
  evaluate/repository_test.go
  go.mod
  go.sum
  language/golang/golang.go
  language/golang/golang_test.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/symflower/symflower.go
  model/symflower/symflower_test.go
  provider/openrouter/openrouter.go
  provider/provider.go
  provider/symflower/symflower.go
  provider/testing/mock.go
  tools/symflower.go
  tools/tools.go
Labels: refactor

#59 fix, Distinguish between available models and models for evaluation so not all are reported
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
Labels: bug

#60 Let language decide test file paths instead of hardcoding that
  language/golang/golang.go
  language/language.go
  language/testing/mock.go
  model/llm/llm.go
Labels: refactor

#53 fix, Log command outputs into the repository logs as well
  cmd/eval-dev-quality/cmd/command.go
  cmd/eval-dev-quality/cmd/command_test.go
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  cmd/eval-dev-quality/cmd/install-tools.go
  cmd/eval-dev-quality/cmd/install-tools_test.go
  cmd/eval-dev-quality/main.go
  evaluate/repository.go
  evaluate/repository_test.go
  language/golang/golang.go
  language/golang/golang_test.go
  language/language.go
  language/testing/mock.go
  log/logger.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/model.go
  model/symflower/symflower.go
  model/symflower/symflower_test.go
  model/testing/mock.go
  tools/symflower.go
  tools/symflower_test.go
  tools/tools.go
  util/exec.go
Labels: bug

#63 Better compatibility to add a new language
  language/golang/language.go
  language/golang/language_test.go
  language/language.go
  language/testing/mock.go
  model/llm/llm.go
Labels: enhancement, refactor

#65 Symflower binary overwrite
  cmd/eval-dev-quality/cmd/evaluate.go
  model/llm/llm.go
  model/symflower/symflower.go
  tools/symflower.go
Labels: enhancement

#66 Generate mocks so there is no more manual work when our interfaces change
  .github/workflows/go.yml
  .mockery.yml
  Makefile
  evaluate/report/collection_test.go
  evaluate/report/csv_test.go
  language/testing/Language_mock_gen.go
  language/testing/helper.go
  language/testing/mock.go
  model/llm/llm_test.go
  model/testing/Model_mock_gen.go
  model/testing/helper.go
  model/testing/mock.go
  provider/testing/Query_mock_gen.go
  provider/testing/mock.go
Labels: enhancement

#71 fix, Use "mockery" version 2.40.3 instead of 2.42.3 to not upgrade to Go 1.22 just yet
  Makefile
  language/testing/Language_mock_gen.go
  model/testing/Model_mock_gen.go
  provider/testing/Query_mock_gen.go
Labels: bug

#70 fix, Allow whitespace after code tags to properly detect code blocks, and split LLM logging into request and response
  .mockery.yml
  language/testing/Language_mock_gen.go
  log/logger.go
  model/llm/llm.go
  model/llm/prompt/parse.go
  model/llm/prompt/parse_test.go
  model/testing/Model_mock_gen.go
Labels: bug, enhancement

#57 Reporting with MarkDown file and SVG bar charts
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/metrics/category.go
  evaluate/metrics/category_test.go
  evaluate/report/markdown.go
  evaluate/report/markdown_test.go
  evaluate/report/testdata/all_categories.svg
  evaluate/report/testdata/empty.svg
  evaluate/report/testdata/two_categories.svg
  evaluate/report/testdata/two_models.svg
  evaluate/version.go
  go.mod
  go.sum
Labels: enhancement

#77 Link models to their log directories in report for convenience
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/report/markdown.go
  evaluate/report/markdown_test.go
  evaluate/repository.go
Labels: enhancement

#76 Release version 0.4.0
  cmd/eval-dev-quality/cmd/evaluate_test.go
  docs/reports/v0.4.0/2/README.md
  docs/reports/v0.4.0/3/README.md
  docs/reports/v0.4.0/4/README.md
  docs/reports/v0.4.0/5/README.md
  evaluate/version.go
Labels: enhancement
