Repository symflower/eval-dev-quality, pull requests merged in 2024-10, with the labels that each got.

#348 Fix typos in Ruby README paths and update to new deep dive
  README.md
Labels: bug, documentation

#337 Write run count to CSV report
  cmd/eval-dev-quality/cmd/evaluate_test.go
  cmd/eval-dev-quality/cmd/report_test.go
  docs/reports/v0.6/evaluation-by-language-score.csv
  docs/reports/v0.6/evaluation-by-language.csv
  docs/reports/v0.6/evaluation-by-model.csv
  docs/reports/v0.6/evaluation-by-symflower-fix.csv
  docs/reports/v0.6/evaluation-by-task-by-language.csv
  docs/reports/v0.6/evaluation-by-task-score.csv
  docs/reports/v0.6/evaluation-by-task.csv
  docs/reports/v0.6/evaluation-cases.csv
  docs/reports/v0.6/evaluation-reliability.csv
  docs/reports/v0.6/evaluation.csv
  evaluate/evaluate.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  go.mod
  go.sum
  scripts/reliability/main.go
Labels: enhancement

#349 Script to convert all SVG files to PNG with Inkscape
  scripts/convert_svg_to_png.sh
Labels: enhancement

#352 Clarify wording, logs, debugging regarding symflower fix
  evaluate/evaluate_test.go
  evaluate/task/symflower.go
  evaluate/task/task-transpile.go
  evaluate/task/task-write-test.go
Labels: refactor

#353 Simplify assessment cleanup for tests
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate_test.go
  evaluate/metrics/testing/assessments.go
  evaluate/report/collection_test.go
  evaluate/task/testing/task.go
  model/llm/llm_test.go
  model/llm/prompt/parse_test.go
  model/symflower/symflower_test.go
Labels: refactor

#354 Always apply "symflower fix" and refactor "write test" task and LLM prompting to prepare for templates
  evaluate/task/task-transpile.go
  evaluate/task/task-write-test.go
  evaluate/task/task-write-test_test.go
  model/llm/llm.go
  model/llm/llm_test.go
Labels: refactor

#351 "Write-test" task with Symflower Smart Test Template as base
  evaluate/task/task-transpile.go
  evaluate/task/task-write-test.go
  evaluate/task/task-write-test_test.go
  model/llm/llm.go
  model/llm/llm_test.go
Labels: enhancement

#355 Install and run some Go linters
  .github/workflows/branch.yml
  .github/workflows/ci.yml
  .github/workflows/job-docker.yml
  .github/workflows/job-lint.yml
  .github/workflows/job-test.yml
  .github/workflows/release.yml
  .vscode/settings.json
  Makefile
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/report.go
  cmd/eval-dev-quality/cmd/report_test.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/metrics/testing/assessments.go
  evaluate/report/csv.go
  evaluate/task/code-repair.go
  evaluate/task/code-repair_test.go
  evaluate/task/task.go
  evaluate/task/test-integration/task_test.go
  evaluate/task/testing/task.go
  evaluate/task/transpile.go
  evaluate/task/transpile_test.go
  evaluate/task/write-test.go
  evaluate/task/write-test_test.go
  language/golang/language_test.go
  language/java/language.go
  language/java/language_test.go
  language/language.go
  language/testing/language.go
  log/logger.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/symflower/symflower.go
  model/symflower/symflower_test.go
  provider/openai-api/query.go
  provider/openrouter/openrouter.go
  scripts/ollama-models/main.go
  scripts/openrouter-models/main.go
  scripts/reliability/main.go
  tools/ollama.go
  util/exec.go
Labels: enhancement

#356 Remove category SVG from the report, because we are moving to a leaderboard
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  cmd/eval-dev-quality/cmd/report.go
  cmd/eval-dev-quality/cmd/report_test.go
  evaluate/report/markdown.go
  evaluate/report/markdown_test.go
  evaluate/report/testdata/all_categories.svg
  evaluate/report/testdata/empty.svg
  evaluate/report/testdata/two_categories.svg
  evaluate/report/testdata/two_models.svg
  go.mod
  go.sum
Labels: enhancement

#359 fix, Use all the rules of Go linter "revive" but exclude some that do not make sense and exit "1" on errors, always
  Makefile
  cmd/eval-dev-quality/cmd/report.go
  conf/language/golang/revive.toml
  evaluate/evaluate.go
  evaluate/report/collection_test.go
  language/golang/language.go
  log/logger.go
  log/logger_test.go
  model/testing/helper.go
  provider/ollama/ollama_test.go
  scripts/max-score/main.go
  scripts/ollama-models/main.go
  tools/install.go
  util/exec_test.go
Labels: bug, enhancement

#357 Remove categorization and total score of reporting, and the "report" command
  README.md
  cmd/eval-dev-quality/cmd/command.go
  cmd/eval-dev-quality/cmd/command_test.go
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  cmd/eval-dev-quality/cmd/report.go
  cmd/eval-dev-quality/cmd/report_test.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/metrics/category.go
  evaluate/metrics/category_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  evaluate/report/markdown.go
  evaluate/report/markdown_test.go
Labels: enhancement

#358 "Write-test" task with Symflower Smart Test Template as base
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate_test.go
  evaluate/task/symflower.go
  evaluate/task/task.go
  evaluate/task/test-integration/task_test.go
  evaluate/task/transpile.go
  evaluate/task/write-test.go
  evaluate/task/write-test_test.go
  language/golang/language.go
  language/java/language.go
  language/language.go
  language/ruby/language.go
  language/testing/Language_mock_gen.go
  model/llm/llm.go
  model/llm/llm_test.go
Labels: enhancement

#361 VSCode recommended extensions and debugging configuration
  .vscode/extensions.json
  .vscode/launch.json
Labels: enhancement

#360 fix, Solving Plain once (with or without template) is enough to not get disqualified
  evaluate/evaluate.go
  evaluate/evaluate_test.go
Labels: bug

#362 Enable Symflower linter by default in VSC
  .vscode/settings.json
Labels: enhancement
