Repository symflower/eval-dev-quality, pull requests merged in 2025-01, with the labels that each got.

#376 New task for code migration
  .mockery.yml
  evaluate/task/migrate.go
  evaluate/task/migrate_test.go
  evaluate/task/repository.go
  evaluate/task/symflower.go
  evaluate/task/task.go
  evaluate/task/write-test.go
  model/capability.go
  model/llm/llm.go
  model/llm/llm_test.go
  model/testing/CapabilityMigrate_mock_gen.go
  model/testing/helper.go
  scripts/evaluation/v0.7-testdrive-migration.sh
  testdata/java/migrate-plain/pom.xml
  testdata/java/migrate-plain/repository.json
  testdata/java/migrate-plain/src/main/java/com/eval/Decrement.java
  testdata/java/migrate-plain/src/main/java/com/eval/Increment.java
  testdata/java/migrate-plain/src/test/java/com/eval/DecrementTest.java
  testdata/java/migrate-plain/src/test/java/com/eval/IncrementTest.java
Labels: enhancement

#369 Remove scoring from within the evaluation and remove and lint unused functions
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate_test.go
  evaluate/metrics/assessment.go
  evaluate/metrics/assessment_test.go
  evaluate/report/collection.go
  evaluate/report/collection_test.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  evaluate/report/markdown.go
  evaluate/report/markdown_test.go
  evaluate/task/code-repair.go
  evaluate/task/code-repair_test.go
  evaluate/task/migrate_test.go
  evaluate/task/symflower.go
  evaluate/task/test-integration/task_test.go
  evaluate/task/transpile.go
  evaluate/task/transpile_test.go
  evaluate/task/write-test_test.go
Labels: refactor

#377 Lint unused code in GitHub Actions
  Makefile
  scripts/deadcode/main.go
Labels: enhancement, CI

#378 Remove assessment collection
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/metrics/testing/assessments.go
  evaluate/report/collection.go
  evaluate/report/collection_test.go
  evaluate/report/testing/csv.go
Labels: refactor

#379 JSON, structured logging
  cmd/eval-dev-quality/cmd/command.go
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  cmd/eval-dev-quality/cmd/install-tools_test.go
  cmd/eval-dev-quality/cmd/version.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/task/code-repair.go
  evaluate/task/migrate.go
  evaluate/task/repository.go
  evaluate/task/symflower.go
  evaluate/task/task.go
  evaluate/task/test-integration/task_test.go
  evaluate/task/transpile.go
  evaluate/task/write-test.go
  evaluate/task/write-test_test.go
  go.mod
  go.sum
  language/coverage.go
  log/logger.go
  log/logger_test.go
  log/multi.go
  model/llm/llm.go
  provider/ollama/ollama_test.go
  tools/install.go
  tools/install_test.go
  tools/ollama.go
  tools/symflower.go
  tools/tools.go
  util/exec.go
Labels: refactor

#393 Upgrade Symflower to v45435 to include license changes
  .github/workflows/ci.yml
  .github/workflows/job-test.yml
  cmd/eval-dev-quality/cmd/command.go
  cmd/eval-dev-quality/cmd/evaluate.go
  scripts/gitlab-ci-symflower-license/main.go
  scripts/gitlab-ci/main.go
  tools/install.go
  tools/symflower.go
Labels: enhancement

#388 Clarify roadmap/release process
  .github/ISSUE_TEMPLATE/3-roadmap.md
Labels: documentation

#394 Clean up container images on GitHub
  .github/workflows/ci.yml
  .github/workflows/job-container-image-build.yml
  .github/workflows/job-container-image-cleanup.yml
  .github/workflows/job-test.yml
  .gitignore
  scripts/github-ci-symflower-license/main.go
  scripts/github-ci/main.go
Labels: enhancement

#396 Build container images on tagging releases
  .github/workflows/job-container-image-build.yml
Labels: enhancement

#392 Save maximum scores for cases and write CSV per case
  cmd/eval-dev-quality/cmd/evaluate_test.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  evaluate/metrics/testing/assessments.go
  evaluate/report/csv.go
  evaluate/report/csv_test.go
  evaluate/report/testing/csv.go
  evaluate/task/code-repair.go
  evaluate/task/code-repair_test.go
  evaluate/task/migrate.go
  evaluate/task/migrate_test.go
  evaluate/task/test-integration/task_test.go
  evaluate/task/testing/task.go
  evaluate/task/transpile.go
  evaluate/task/transpile_test.go
  evaluate/task/write-test.go
  evaluate/task/write-test_test.go
  task/config.go
  task/config_test.go
  task/task.go
  testdata/golang/light/repository.json
  testdata/golang/mistakes/repository.json
  testdata/golang/plain/repository.json
  testdata/golang/transpile/repository.json
  testdata/java/light/repository.json
  testdata/java/mistakes/repository.json
  testdata/java/plain/repository.json
  testdata/java/transpile/repository.json
  testdata/ruby/light/repository.json
  testdata/ruby/mistakes/repository.json
  testdata/ruby/plain/repository.json
  testdata/ruby/transpile/repository.json
Labels: enhancement

#391 Release script for tagging and updating the binary version
  .github/ISSUE_TEMPLATE/3-roadmap.md
  evaluate/version.go
  go.mod
  go.sum
  scripts/eval-dev-quality-release/main.go
Labels: enhancement

#397 Clarify order of tasks for a release
  .github/ISSUE_TEMPLATE/3-roadmap.md
Labels: documentation

#400 fix, Retry resetting repository if "git clean" fails
  evaluate/task/repository.go
Labels: bug

#401 Update "github.com/zimmski/osutil" to v1.3.0 to sync with local repository
  go.mod
  go.sum
Labels: enhancement

#402 fix, Multiply the "tests-passing" values of transpile tasks because we are transpiling for two languages and therefore we are also running twice the tests
  testdata/golang/transpile/repository.json
  testdata/java/transpile/repository.json
  testdata/ruby/transpile/repository.json
Labels: bug
