Repository symflower/eval-dev-quality, pull requests merged in 2025-03, with the labels that each got.

#431 Integrate v1.0 results
  README.md
  docs/cta.svg
Labels: documentation, enhancement

#437 Keep last 5 container images having a version tag
  .github/workflows/job-container-image-cleanup.yml
Labels: CI

#432 Upgrade Go to 1.24.1 (from 1.23.6) and all Go packages
  .github/workflows/job-lint.yml
  .github/workflows/job-test.yml
  Dockerfile
  Makefile
  cmd/eval-dev-quality/cmd/command.go
  evaluate/evaluate_test.go
  evaluate/task/transpile_test.go
  evaluate/task/write-test_test.go
  go.mod
  go.sum
  language/testing/Language_mock_gen.go
  log/logger.go
  model/testing/CapabilityMigrate_mock_gen.go
  model/testing/CapabilityRepairCode_mock_gen.go
  model/testing/CapabilityTranspile_mock_gen.go
  model/testing/CapabilityWriteTests_mock_gen.go
  model/testing/Model_mock_gen.go
  provider/testing/Loader_mock_gen.go
  provider/testing/Provider_mock_gen.go
  provider/testing/Puller_mock_gen.go
  provider/testing/Query_mock_gen.go
  scripts/deadcode/main.go
  scripts/eval-dev-quality-release/main.go
  tools/symflower.go
  tools/testing/Tool_mock_gen.go
Labels: enhancement

#412 CLI flag for specifying a run ID starting index to be able to distribute runs
  cmd/eval-dev-quality/cmd/evaluate.go
  evaluate/evaluate.go
  evaluate/evaluate_test.go
  go.mod
  go.sum
Labels: enhancement
