Repository symflower/eval-dev-quality, pull requests merged in 2025-02, with the labels that each got.

#408 Allow to set reasoning_effort for models (e.g. OpenAI's o3-mini)
  cmd/eval-dev-quality/cmd/evaluate.go
  cmd/eval-dev-quality/cmd/evaluate_test.go
  cmd/eval-dev-quality/cmd/init_test.go
  evaluate/evaluate_test.go
  go.mod
  go.sum
  model/llm/llm.go
  model/llm/llm_test.go
  model/model.go
  model/symflower/symflower.go
  model/testing/Model_mock_gen.go
  provider/ollama/ollama.go
  provider/openai-api/openai.go
  provider/openai-api/query.go
  provider/openrouter/openrouter.go
  provider/provider.go
  provider/testing/Query_mock_gen.go
Labels: enhancement

#413 Upgrade Go to 1.23.6 (from 1.21.5)
  .github/workflows/job-lint.yml
  .github/workflows/job-test.yml
  Dockerfile
  Makefile
  cmd/eval-dev-quality/cmd/evaluate.go
  evaluate/task/symflower.go
  evaluate/task/write-test_test.go
  go.mod
  go.sum
  language/golang/language.go
  language/golang/language_test.go
  scripts/deadcode/main.go
  scripts/eval-dev-quality-release/main.go
  testdata/golang/light/go.mod
  testdata/golang/mistakes/importMissing/go.mod
  testdata/golang/mistakes/openingBracketMissing/go.mod
  testdata/golang/mistakes/syntaxErrorTypeMissing/go.mod
  testdata/golang/mistakes/typeUnknown/go.mod
  testdata/golang/mistakes/variableUnknown/go.mod
  testdata/golang/plain/go.mod
  testdata/golang/transpile/balancedBrackets/go.mod
  testdata/golang/transpile/binarySearch/go.mod
  testdata/golang/transpile/cascadingIfElse/go.mod
  testdata/golang/transpile/isSorted/go.mod
  testdata/golang/transpile/pascalsTriangle/go.mod
Labels: enhancement

#416 Replace "Inkscape" with "svgexport"
  .github/workflows/job-container-image-build.yml
  Dockerfile
  scripts/convert_svg_to_png.sh
Labels: enhancement, CI

#418 Bump symflower version to v46727 (from 45435)
  tools/symflower.go
Labels: dependencies
